export const typographyAliases = {
  t1: 'text-xxl',
  t2: 'text-xl',
  t3: 'text-l',
  t4: 'text-m',
  t5: 'text-s',
  t6: 'text-xs',
  h5: 'text-s font-bold',
  h4: 'text-m font-bold',
  h3: 'text-l font-bold',
  h2: 'text-xl font-bold',
  h1: 'text-xxl font-bold',
  'text-display': 'text-xxxl',
  'text-preamble': 'text-ml',
  'text-body': 'text-m',
  'text-caption': 'text-s',
  'text-detail': 'text-xs',
};