name: Release
on:
  push:
    branches:
      - main
      - beta
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v1
        with:
          runtime: node@lts
          cache: true
          install: true
      - run: pnpm test
      - run: pnpm build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
