name: Update next
on:
  workflow_run:
    workflows:
      - Release
    branches:
      - master
    types: completed
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Rebase next to master
        run: |
          git fetch --unshallow
          git checkout next
          git rebase origin/master
          git push